import type { ImpactGridState } from './types';

export type ImpactGridLook = 'breakpoint' | 'mosaic' | 'rough' | 'rip';

/** Named looks spanning the module's range. Each is a state patch — seed,
 *  pens/inks, and the drawn trajectory are never touched. */
export const IMPACT_GRID_LOOKS: Record<
  ImpactGridLook,
  { label: string; state: Partial<ImpactGridState> }
> = {
  breakpoint: {
    label: 'Breakpoint bars',
    state: {
      layout: 'bars',
      sizeVariation: 0.25,
      positionJitter: 0.03,
      rotationJitter: 0.02,
      gap: 0.1,
      impactStrength: 0,
      shatter: 0.85,
      scatter: 0.35,
      debris: 0.25,
      crush: 0.7,
      sweep: 0.7,
      fill: 1,
      fillStyle: 'texture',
      inkSplit: 0.35,
      inkPath: true,
      wobbleMm: 0,
    },
  },
  mosaic: {
    label: 'Mosaic',
    state: {
      layout: 'grid',
      sizeVariation: 0.15,
      positionJitter: 0.03,
      rotationJitter: 0.02,
      gap: 0.06,
      impactStrength: 0,
      shatter: 0.85,
      scatter: 0.35,
      debris: 0.25,
      crush: 0.7,
      sweep: 0.7,
      fill: 1,
      fillStyle: 'texture',
      inkSplit: 0.35,
      inkPath: true,
      wobbleMm: 0,
    },
  },
  rough: {
    label: 'Rough grid',
    state: {
      layout: 'grid',
      sizeVariation: 0.35,
      positionJitter: 0.25,
      rotationJitter: 0.3,
      gap: 0.15,
      impactStrength: 0.15,
      shatter: 0.7,
      scatter: 0.2,
      debris: 0.2,
      crush: 0.5,
      sweep: 0.2,
      fill: 0,
      fillStyle: 'none',
      inkSplit: 0,
      inkPath: false,
      wobbleMm: 0.25,
    },
  },
  rip: {
    label: 'Rip',
    state: {
      layout: 'grid',
      sizeVariation: 0.35,
      positionJitter: 0.25,
      rotationJitter: 0.3,
      gap: 0.15,
      impactStrength: 0.7,
      shatter: 0.6,
      scatter: 0.7,
      debris: 0.4,
      crush: 0.4,
      sweep: 0,
      fill: 0.2,
      fillStyle: 'hatch',
      inkSplit: 0,
      inkPath: false,
      wobbleMm: 0.25,
    },
  },
};
